### PR TITLE
refractor: change attribute shell to backend

### PR DESCRIPTION
**Pull request by abhijeetSaroha**
Solves #110

### CODE REVIEW

**Comment by abhijeetSaroha** [comment]
Can you please review whenever you have time? @xmnlab

**Comment by abhijeetSaroha** [comment]
I have also updated the `.github/workflow` .yaml files. Is this okay or will it remain same like before?

**Comment by abhijeetSaroha** [comment]
I have reverted the changes to `.github/workflow` .yaml files.

**Comment by abhijeetSaroha** [comment]
To update the documentation, I found two files `.ipynb` in `docs/tutorial`, where `shell` needs to be changed to `backend`, but two more files `changlog.md` and `xonsh.md` , should I change too (I don't think so), can you please check it?

**Comment by xmnlab** [comment]
thanks for working on that @abhijeetSaroha

**Pull request merged**
