### PR TITLE
docs: add small section about xonsh and fix old style documentation

### LINKED ISSUE #44: Add small section about xonsh
We need a small section about xonsh.

* So first, it is important to mention that xonsh is the shell app used by default
* Explain how to use other shell apps (we have a bunch of examples at the tests/.makim*.yaml
* Show some important differences about bash and xonsh and point out the user to more information https://xon.sh/bash_to_xsh.html

### PR DESCRIPTION
**Pull request by abhijeetSaroha**
resolve #44

### CODE REVIEW

**Comment by xmnlab** [comment]
@abhijeetSaroha ,

the CI pointed some style issue here https://github.com/osl-incubator/makim/actions/runs/6859379368/job/18659921382?pr=60#step:6:15

that means that the file you changed need to ends with one empty new line (some information here https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3)

**Comment by abhijeetSaroha** [comment]
Hi @xmnlab , I have resolved the issue, can you please check it. 
* Remove the unwanted content form README.md file 
* add empty new line in the end

**Comment by xmnlab** [comment]
@abhijeetSaroha , that looks great! thanks!

just one last thing, could you keep the line with less than 80 characters please?
if you are using vscode there are some autoformatter for markdown that can help you
I don't remember if `prettier` can handle markdown as well

**Comment by abhijeetSaroha** [comment]
@xmnlab done that, could you please check now?

**Review by xmnlab — APPROVED** [review]
Looks good to me (LGTM), thanks @abhijeetSaroha !
congrats for your first PR merged here :)

**Pull request merged**
